### ISSUE TITLE
pepper_dcm_controllers package missing

### ISSUE THREAD

**Issue by raghunaik2009** [ros-naoqi/pepper_gazebo_plugin#1]
I'm not able to find pepper_dcm_controllers package. Plugin is not working properly with ros indigo and  gazebo version 2.2.3.

**Comment by nlyubova** [comment]
Write, because it is not public yet :) it will be published soon but even with it, you cannot do trajectory control, I will try to fix it one day. However position control works !

**Comment by raghunaik2009** [comment]
Thanks for the reply. :) Even configuration parameters are not yet available. So I am unable to run Pepper robot with Gazebo simulator. I'm facing another issue with Nao Gazebo plugin, whenever i run nao gazebo plugin, its fingers are shaking. How can i fix this issue? Is the issue with PID tuning?

**Comment by nlyubova** [comment]
Config files for Pepper are available, if not, check my pull request

Yes, nao fingers are shaking, If you find the reason, do a pull request 

Good luck!

**Comment by nlyubova** [comment]
pepper_dcm_control can be found here:  
https://github.com/ros-naoqi/pepper_virtual

**Comment by nlyubova** [comment]
Thé config params are available here: https://github.com/ros-naoqi/pepper_robot/tree/master/pepper_description/urdf/pepper1.0_generated_urdf

**Comment by nlyubova** [comment]
Just tested planning trajectories with MoveIt and Gazebo, and now it works, You only need to pull last changes in pepper_moveit_config

**Comment by raghunaik2009** [comment]
Thank You. One more question is it possible to connect ROS to Virtual NAO?

**Comment by nlyubova** [comment]
it is better to ask it here: https://github.com/ros-naoqi/nao_virtual/issues
