### ISSUE TITLE
compatibility experiment / gazebo

### ISSUE THREAD

**Issue by lengagne** [ros-naoqi/pepper_gazebo_plugin#11]
Hi,
when I use the actual robot I got access to the topic /joint_angles
and with gazebo I got /pepper_dcm/JOINTNAME_position_controller/command.

I did not find how to get the same topic (/joint_angles) in simulation. Do you have any clue ?

Can you help me ?

**Comment by nlyubova** [comment]
Hello, 
this package was made to control each joint one by one. If you need to control /joint_angles, then Naoqi Driver package should be enpough
