### ISSUE TITLE
Kinetic issue with controller in Gazebo

### ISSUE THREAD

**Issue by warp1337** [ros-naoqi/pepper_gazebo_plugin#12]
I installed all packages (for kinetic) as mentioned in the [ReadMe](https://github.com/ros-naoqi/pepper_virtual/tree/master/pepper_gazebo_plugin). 
However, I get the following error that indicates (IMHO) that the 
corresponding controller cannot be loaded.

<code>

PARAMETERS
 * /pepper_dcm/Head_controller/joints: ['HeadYaw', 'Head...
 * /pepper_dcm/Head_controller/type: position_controll...
 * /pepper_dcm/LeftArm_controller/joints: ['LShoulderPitch'...
 * /pepper_dcm/LeftArm_controller/type: position_controll...
 * /pepper_dcm/LeftHand_controller/joints: ['LHand']
 * /pepper_dcm/LeftHand_controller/type: position_controll...
 * /pepper_dcm/Pelvis_controller/joints: ['HipRoll', 'HipP...
 * /pepper_dcm/Pelvis_controller/type: position_controll...
 * /pepper_dcm/RightArm_controller/joints: ['RShoulderPitch'...
 * /pepper_dcm/RightArm_controller/type: position_controll...
 * /pepper_dcm/RightHand_controller/joints: ['RHand']
 * /pepper_dcm/RightHand_controller/type: position_controll...
 * /pepper_dcm/Wheels_controller/joints: ['WheelFL', 'Whee...
 * /pepper_dcm/Wheels_controller/type: position_controll...
 * /pepper_dcm/joint_state_controller/publish_rate: 50
 * /pepper_dcm/joint_state_controller/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.6
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    pepper_trajectory_controller (controller_manager/spawner)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [16343]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ba0db4f2-f521-11e6-af70-9890969b8671
process[rosout-1]: started with pid [16356]
started core service [/rosout]
process[gazebo-2]: started with pid [16369]
process[gazebo_gui-3]: started with pid [16376]
process[pepper_trajectory_controller-4]: started with pid [16385]
process[spawn_urdf-5]: started with pid [16387]
[ INFO] [1487343589.687508533]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1487343589.689367997]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1487343589.921023, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[spawn_urdf-5] process has finished cleanly
log file: /home/fl/.ros/log/ba0db4f2-f521-11e6-af70-9890969b8671/spawn_urdf-5*.log
[WARN] [1487343620.146810, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[pepper_trajectory_controller-4] process has finished cleanly

</code>

**Comment by warp1337** [comment]
It seems I have somehow messed up my Gazebo installation. Closing.

**Comment by blevesque** [comment]
Hi warp, do you know what was wrong with your gazebo installation ?

**Comment by kosenhitatchi** [comment]
Hello @warp1337 I'm happy you solved your problem. What was our version of Gazebo ?
What went wrong in the installation process ?
Thanks
