### ISSUE TITLE
Robot is falling while simulation is on

### ISSUE THREAD

**Issue by michtesar** [ros-naoqi/pepper_gazebo_plugin#14]
When I download all packages and build properly without any error I run a MoveIt! and Gazebo. When I click start simulation in Gazebo robot is starting to falling and clamping the fingers in very strange way.

Is there any way how to solve this? I need to get simulation working as soon as possible.

**Comment by nlyubova** [comment]
Hello, what is your version of Gazebo and ROS? Did you install with apt-get or from sources?

**Comment by michtesar** [comment]
I tried both - first time I installed packages from ros-kinectic-naoqi-pepper-* and then on different machine I build it from source (here on github - pepper_virtual).

I use ROS Kinetic Kame, I believe Gazebo 7 (default one which comes preinstaleld with ROS) and Ubuntu 16.04.3 LTS.

**Comment by rodolfo-picoreti** [comment]
Hi, I have the same problem. I'm using ubuntu xenial with ros kinetic and gazebo 7.11. I also found other persons with the same issue.

https://staff.fnwi.uva.nl/b.terwijn/pepper-lab-book/
http://answers.gazebosim.org/question/18254/pepper-model-falls-at-startup/

**Comment by nlyubova** [comment]
If you use kinetic, do not install it with apt-get, and rather compile it from source with all dependencies

**Comment by nlyubova** [comment]
Moving fingers are ok.

wheels for Pepper are not implemented; if you can fix them in pepper_description, please do. 

For all robots, you can move arms and head

**Comment by tunghustvn** [comment]
I found that the default value of gravity of all fingers is false. I set it true and the fingers are ok but Pepper still fall down.

**Comment by kosenhitatchi** [comment]
@tunghustvn @neuropacabra @nlyubova @rodolfo-picoreti  . I'm actually also trying to solve this issue, as it's quite limitating for my work right now. Let's join forces and solve that together. :muscle::muscle:

**Comment by kosenhitatchi** [comment]
Hello everyone. I hope you're not getting burn by the warn summer sun.
Here is a quick update on the simulator.

I recently came across the work of [Bas Terwijn - Pepper lab book](https://staff.fnwi.uva.nl/b.terwijn/pepper-lab-book/).
By following his step i managed to have a pepper which is not falling down in slow-mo.

[![Video](https://img.youtube.com/vi/ZBl1EsF-uA8/0.jpg)](https://youtu.be/ZBl1EsF-uA8)

I still have to dig a little bit on the controller_manager, but we might be on the good way.

Bye

**Comment by michtesar** [comment]
After couple of tries I end up with Pepper in Gazebo. It is not working and probably never will :-)

**Alternatives:**
OpenAI Gym (soom I will release whole implementation) for Python
DeepMind Control
MORSE https://pub.uni-bielefeld.de/download/2916790/2916921

**Comment by michtesar** [comment]
@kosenhitatchi by using ROS Indigo? What is your status? Are you manager to get it working? @nlyubova do you have any news? This is what I have when using latest GitHub packages https://youtu.be/nTOR73TyN-M

**Comment by kosenhitatchi** [comment]
Hi @michtesar .
Nice computer background ;-)

A quick answer has I'm on the move, and don't have access to pepper anymore.
There actually two issue happening in your video (I was having the same).

The first one is an issue with you gazebo version, this version do not like a type of joint defining the virtual pepper (the "PositionJointInterface" ) which induce this "gravity bug" .

Try to force the upgrade gazebo to his last stable version : Gazebo 9.
It's kinda dirty but if I remember correctly it's what I did (https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612#issuecomment-369634532). In my memory doing this hack with kinetic+ gazebo 9 solve the "gravity bug" on my side.

Cf : https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612

On the other side the sliding motion is induced by a defect in the wheel's controller code, as explained by @nlyubova https://github.com/ros-naoqi/pepper_virtual/issues/14#issuecomment-371569692. I did not managed to fix it.

Keep us in touch with you're progress.

Sincerely

Kosen

**Comment by michtesar** [comment]
Hi Kosen! Nice!

I have managed to get a proper Gazebo simulation working with different packages, but unfortunately I am not able to control a robot with MoveIt! anymore.

```sh
#!/bin/bash

rm -rf ~/pepper_ws

echo "Installing dependencies (you'll be asked for sudo password)..."
sudo apt-get install python-wstool
sudo apt-get install ros-kinetic-moveit*
sudo apt-get install ros-kinetic-gazebo*
sudo apt-get install ros-kinetic-pepper-meshes

echo "Creating Pepper ROS workspace at ~/pepper_ws"
mkdir -p ~/pepper_ws/src
cd ~/pepper_ws/src

git clone https://github.com/awesomebytes/pepper_robot
git clone https://github.com/awesomebytes/pepper_virtual
git clone https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins
git clone https://github.com/awesomebytes/gazebo_model_velocity_plugin.git

echo "Compiling with catkin_tools..."
cd .. && catkin build

source devel/setup.bash

cd ~
echo "Installation is complete! Try some examples..."
```

Right now I am interested in Gazebo simulation with MoveIt! to hook it to the Gazebo-Gym and try some reinforcement learning in pick and place task.

Have a nice weekend! And thank you for your time!

Michael

**Comment by kosenhitatchi** [comment]
Hello @michtesar,
That's a great new. 

Even if you're not able to link MoveIt to it (now), did your installation solved the "gravity bug" ?

What about the wheel controller , are you able to make pepper move using the standard ROS command ( with [http://wiki.ros.org/rqt_ez_publisher](rqt_ez_publishe) or other) ?

Sincerely


Extra question outside of the scope of this thread : Did you managed to have a virtual depth cam in gazebo ?

**Comment by michtesar** [comment]
I guess it solved "gravity bug" and depth and lasers and sonars are included ;-) only Moveit does not work now.
