### ISSUE TITLE
[pepper_gazebo_plugin] pepper becomes a weird shape

### ISSUE THREAD

**Issue by kochigami** [ros-naoqi/pepper_gazebo_plugin#6]
If anyone knows how to handle this problem, could you help me? Sorry for my trouble.

ros: indigo
gazebo version: 2.2.3
gazebo_ros (I use deb) version:  2.4.11-0trusty-20160713-191140-0700
pepper_gazebo_plugin (I use deb) version: 0.0.3-0trusty-20160925-083240-0700
pepper_description version:   0.1.7-0trusty-20160629-000946-0700

１. not execute `source /opt/ros/indigo/setup.bash`

`roslaunch pepper_gazebo_plugin pepper_gazebo_plugin_Y20.launch` returns some errors.

```
ERROR: cannot launch node of type [gazebo_ros/gzserver]: can't locate node [gzserver] in package [gazebo_ros]
ERROR: cannot launch node of type [gazebo_ros/gzclient]: can't locate node [gzclient] in package [gazebo_ros]
process[pepper_trajectory_controller-4]: started with pid [18934]
ERROR: cannot launch node of type [gazebo_ros/spawn_model]: can't locate node [spawn_model] in package [gazebo_ros]
```

２. execute `source /opt/ros/indigo/setup.bash`
`roslaunch pepper_gazebo_plugin pepper_gazebo_plugin_Y20.launch` returns gazebo window, but when I push a play button, pepper transforms into a weird shape.

![weird_pepper](https://cloud.githubusercontent.com/assets/7259671/19338997/a15185c6-915b-11e6-9729-029bee05a336.png)

Before 1 occurs, I could launch gazebo plugin with some packages from source (pepper_description, pepper_gazebo_plugin)
I did `sudo apt-get update` before these problems occurred, but I'm not sure the actual cause.

**Comment by nlyubova** [comment]
hello,

try to source at first source /opt/ros/indigo/setup.bash and then your workspace (for correct workspace overlap). 

By the way, did you compile pepper_gazebo_plugin from source or from apt-get?  there are maybe some missing dependencies

**Comment by kochigami** [comment]
Hi, 
thank you very much for your comment.
I used pepper_gazebo_plugin from source.

I solved my problem when I git cloned `https://github.com/ros-simulation/gazebo_ros_pkgs.git (jade-level)`.
I'm not sure why I had the problem, but I read these articles yesterday.
http://answers.ros.org/question/198929/running-controller_manager-spawner-with-mybotrobot_description/
http://answers.ros.org/question/214712/gazebo-controller-spawner-warning/

**Comment by lengagne** [comment]
Hi, I have the same issue.

When I run the launch file I only have those node : 
/gazebo
/pepper_trajectory_controller
/rosout

I do not have any controllers : (rosservice list | grep controller_manager   does not give results)

I have Kubuntu 14.04, ros indigo and all install from apt-get install .

Do you have any clue ?

**Comment by nlyubova** [comment]
Hi,
Did you follow the previous comments ? It seams that installing https://github.com/ros-simulation/gazebo_ros_pkgs.git can help

**Comment by lengagne** [comment]
Hi, I tried to install the gazebo_ros_pkgs (from apt), indeed it was already installed.
But I still have the problem. From the console I have the following line : 
[INFO] [WallTime: 1477945814.491622] [0.000000] Controller Spawner: Waiting for service controller_manager/load_controller
[WARN] [WallTime: 1477945844.715412] [0.000000] Controller Spawner couldn't find the expected controller_manager ROS interface.

**Comment by lengagne** [comment]
For more information I have those topic : "rostopic list" 
/clock
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/set_link_state
/gazebo/set_model_state
/rosout
/rosout_agg

**Comment by nlyubova** [comment]
maybe, some dependencies are missing./ Could you compile from source this one, please? 

git clone git@github.com:roboticsgroup/roboticsgroup_gazebo_plugins.git

and If it does not work, then try from source while we fix it.

**Comment by lengagne** [comment]
I am sorry, I am quite with ROS

I removed some package with apt-get remove ...

I have those sources : gazebo_ros_pkgs  pepper_dcm_robot  pepper_virtual  roboticsgroup_gazebo_plugins   in my catkin_ws/src

I did catkin_make, then source devel/setup.bash

The command rospack find pepper_gazebo_plugin  gives me : 
~/catkin_ws/install/share/pepper_gazebo_plugin

But I still have the same issue when I run "roslaunch pepper_gazebo_plugin pepper_gazebo_plugin_Y20.launch "

I have the result :
... logging to /home/lengagne/.ros/log/2638b0b4-a108-11e6-8b8c-3ca9f4685120/roslaunch-lengagne-HP-3565.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://lengagne-HP:60513/

# SUMMARY

PARAMETERS
- /pepper_dcm/Head_controller/joints: ['HeadYaw', 'Head...
- /pepper_dcm/Head_controller/type: position_controll...
- /pepper_dcm/LeftArm_controller/joints: ['LShoulderPitch'...
- /pepper_dcm/LeftArm_controller/type: position_controll...
- /pepper_dcm/LeftHand_controller/joints: ['LHand']
- /pepper_dcm/LeftHand_controller/type: position_controll...
- /pepper_dcm/Pelvis_controller/joints: ['HipRoll', 'HipP...
- /pepper_dcm/Pelvis_controller/type: position_controll...
- /pepper_dcm/RightArm_controller/joints: ['RShoulderPitch'...
- /pepper_dcm/RightArm_controller/type: position_controll...
- /pepper_dcm/RightHand_controller/joints: ['RHand']
- /pepper_dcm/RightHand_controller/type: position_controll...
- /pepper_dcm/WheelB_controller/joint: WheelB
- /pepper_dcm/WheelB_controller/type: effort_controller...
- /pepper_dcm/WheelFL_controller/joint: WheelFL
- /pepper_dcm/WheelFL_controller/type: effort_controller...
- /pepper_dcm/WheelFR_controller/joint: WheelFR
- /pepper_dcm/WheelFR_controller/type: effort_controller...
- /pepper_dcm/joint_state_controller/publish_rate: 50
- /pepper_dcm/joint_state_controller/type: joint_state_contr...
- /robot_description: <?xml version="1....
- /rosdistro: indigo
- /rosversion: 1.11.20
- /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    pepper_trajectory_controller (controller_manager/spawner)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [3580]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 2638b0b4-a108-11e6-8b8c-3ca9f4685120
process[rosout-1]: started with pid [3593]
started core service [/rosout]
process[gazebo-2]: started with pid [3615]
process[gazebo_gui-3]: started with pid [3622]
process[pepper_trajectory_controller-4]: started with pid [3626]
process[spawn_urdf-5]: started with pid [3627]
Gazebo multi-robot simulator, version 2.2.3
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Gazebo multi-robot simulator, version 2.2.3
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

Msg Waiting for master.[ INFO] [1478096706.652061135]: Finished loading Gazebo ROS API Plugin.
Msg Waiting for master[ INFO] [1478096706.652726170]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...

Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.1.36
[INFO] [WallTime: 1478096706.923169] [0.000000] Controller Spawner: Waiting for service controller_manager/load_controller

Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.1.36
[spawn_urdf-5] process has finished cleanly
log file: /home/lengagne/.ros/log/2638b0b4-a108-11e6-8b8c-3ca9f4685120/spawn_urdf-5*.log
Error [Param.cc:181] Unable to set value [1,0471975511965976] for key[horizontal_fov]
Error [Param.cc:181] Unable to set value [0,100000001] for key[near]

Maybe I did something wrong, (as I told you I am quite new with ROS)

**Comment by lengagne** [comment]
And no problem (except shaking fingers) with nao

**Comment by lengagne** [comment]
I installed everything from source (except pepper_meshes) and it solves this issue.
