### ISSUE TITLE
Controllers don't charge on simulated Pepper

### ISSUE THREAD

**Issue by jfermes** [ros-naoqi/pepper_gazebo_plugin#8]
Hi,

We have installed all packages from repository:

sudo apt-get install ros-indigo-pepper*

Moveit works perfectly, but when we launch a simulated Pepper in Gazebo, we don't see the controllers in the topics. We start the simulation pressing play button and the robot just collapses.

Are we missing something?

We saw a github repository to be cloned in our workspace:
git clone git@github.com:roboticsgroup/roboticsgroup_gazebo_plugins.git

But we have no access. Is this necessary? Do we need to install something else by hand?

We are using Ubuntu 14.10 with Indigo.

Thank you very much

**Comment by nlyubova** [comment]
Hello,
which Ubuntu, ROS and Gazebo version do you use? 

If you want to clone roboticsgroup_gazebo_plugins, just do
git clone https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins
and compile it with catkin_make.

You can also try to compile all pepper packages from source, it could help.
For us, it works fine on Indigo but not on Kinetic yet

Let us know, if you can solve it,
Natalia

**Comment by reinzor** [comment]
Same problem here:

- Ubuntu 16.04 x64 
- ROS Kinetic desktop full

Pepper packages installed:

    sudo apt install ros-kinetic-pepper-*

When I run the following command:

    roslaunch pepper_gazebo_plugin pepper_gazebo_plugin_Y20.launch

The gazebo sim boots but when i press play, the robot collapses. Also no sensor and actuator topics available

Console output:

    [INFO] [WallTime: 1484647970.508746] [0.000000] Controller Spawner: Waiting for service controller_manager/load_controller
    [WARN] [WallTime: 1484648000.647602] [0.000000] Controller Spawner couldn't find the expected controller_manager ROS interface.

I was looking through the pepper_description but I don't see any gazebo references for sensor (laserscan, cameras etc) and/or controller interfaces (gazebo_ros_control), is this correct?

**Comment by reinzor** [comment]
I just tried with the latest Github versions, this seems to work:

    git clone https://github.com/ros-naoqi/pepper_virtual.git
    git clone https://github.com/ros-naoqi/pepper_robot.git
    roslaunch pepper_gazebo_plugin pepper_gazebo_plugin_Y20.launch

Apparently , all gazebo specific xml tags are not present in the debian release yet.

**Comment by mikaelarguedas** [comment]
You are right, `pepper_description` has not been released since the Gazebo tags have been added so they are not part of the debian packages yet.
I created https://github.com/ros-naoqi/pepper_robot/issues/33 to track it, the maintainer will release them soon.

Thanks @reinzor for the accurate bug report!

**Comment by mikaelarguedas** [comment]
this should be fixed now that `pepper_robot` has been released (c.f. https://github.com/ros-naoqi/pepper_robot/issues/33). It will take a few weeks before being synced to the main repo.

Closing this
